name: Deploy to gh-pages branch

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    - name: Deploy
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
      run: |
        set -ex
        git remote set-url origin https://netdefender:${ACCESS_TOKEN}@github.com/netdefender/WebPackPlayGround.git 
        git push origin `git subtree split --prefix public master`:gh-pages --force
